language: node_js
node_js:
- '12'
install:
- npm install -g codecov
before_script:
- yarn
script:
- yarn test && codecov
deploy:
  provider: npm
  email: alpha.wong@tuta.io
  api_key:
    secure: AGvyHsXE3FEqOj74xOfPQh1FPLBOLhn59A3Q+mPCsGCsFJKx0jm6/LVm2ZNJV6n8E+M38UYkzxGUIJ4jtXKnzmWrgztV8hjxvk9RbB5rGTp4r4mwRHTAm9qOHeQKJnizqhQyzXTPMHTEuLNSvM9aQVJQXJc4bh+9YXDnAx6yW2+GOwBfF5OviS91FPMgOdDGRavcfg3I3KXwbLQr8h3kGmvVRG7IOWUxsxj6FuG3QPJCNl13XoKbLWZEEkfp0J7T1b67R+ZBu1PYyay13JxUVvhpPHZtP92AOJv4Ll2vLzjI5Cd86HYiijzziF09h8eT2Z92O4kX0sVQKnW4EApO7ZmRQu1ZntDE3PvXdmRtbhI6aJW7sAsB3PVJZoxxed0PqsW+5SPmSpPBZiB3mfCqoRnfjbKJzPcqJEKzrs0J/RrR5kJ5DCk/x2gyFE2WyuJRTPXHTEAPyeGlKEtjM2EKmcgo3ab/nAFBQEAbknGZrUWW10S+LwoNmsKmX3ja14WgG5Df2YiNbQvx/3+0V7OP9jfzGXKVonPxEG80+SGyX3JBoS4IwgF8chsJMIEnT/4f1hR3MYSXM+RpNRuyICK+C9wDZkr3CORsH140Wi7tktZmI8IMIKFyfFLkRCKnNjKtaHYrYHhRM80Cp64VvnHcCGFjXUuZl2kt8pL6MQ139ZQ=
  on:
    tags: true
    repo: AlphaWong/insightops-client
