language: node_js
node_js:
- '12'
install:
- npm install -g codecov
before_script:
- yarn
script:
- yarn test && codecov
deploy:
  provider: npm
  email: alpha.wong@tuta.io
  api_key:
    secure: ju7qJRsixjYDpthYCLNb/bD5QS8wA0Ik2wQ8JxK+eWR+spGloB3vEOoT8yaXM37KQwW/QoKw7JGlmyYbtHNW6B/dMUYjNvsNl4eT2V/S6lyJ/YLZOaIe/ew5SC5OYa141RftPKntzId0kaLXbTM+qA0Av2IEltvoQjV0d+Y1Kqj+1/BdgxE7w0U83jeN0sdU4bWj+mIjkgZ9xKNfdl954snRSsfXpXqc1gbdNNhrvziHlDFMk3j4B8771FlIYB0AjQQ3RFp/uQLHZVwb9vTcjQKiB2tmvlyEXNY76Vy2OPLF/5ZTEgbDMvmLkZmj7OmjMFRvodlpfauPtu3tLTcOcmW+Uk4CNgWOarRjWCb520W+VzjUfNTpIkIt5IygdmlA7NfdnMuJFkmtwjvRtwsdBKHDLcoDzqxffcbCRtBvaE4Xcv1yc0zSrJnV39JN2yk+LrhFENlrLrqzBBjUm7IK1G/iKT63ICsXwCi0yzl7PYl9qkSWYHht1dz4mmsTo79xivJ89MsJjg14/v9ZQXwS80bmTBJEK1aiW/DIR5yaiYRNxTP8aQGjNLs0xcIgHhe5k8rYiidJJBGZtgvPSUiHVBQFDCZeKowXVwQHVRujH5oEbZK3OxYtoq7Der/1MEZNZNEYWZlC3B89yAJa30//WqHp4dxxjY3WEgceKEC5BpM=
  on:
    tags: true
    repo: AlphaWong/insightops-client
