language: node_js
node_js:
  - '12'
install:
  - npm install -g codecov
before_script:
  - yarn
script:
  - yarn test && codecov

deploy:
  provider: npm
  email: 'alpha.wong@tuta.io'
  on:
    tags: true
